language: ruby
rvm:
    - 2.1
script: ./cibuild

env:
      global:
            - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
notifications:
    email:
        - contact@evidex.me
    on_success: change
    on_failure: always
